### ISSUE TITLE
Support for .zprint.edn

### ISSUE THREAD

**Issue by ghost** [rflagreca/vscode-clj-zprint#1]
Thanks for this very useful extension!

In the [zprint documentation](https://cljdoc.org/d/zprint/zprint/0.5.1/doc/documentation#how-to-configure-zprint), I found that:

> it will look in the current directory for a file `.zprintrc` and if it doesn't find one, it will look for `.zprint.edn`.

However, this extension only seems to support `.zprintrc` and not `.zprint.edn`, which I would prefer to use.

I initially raised this issue [at the `zprint` repo](https://github.com/kkinnear/zprint/issues/210), but the owner indicated that the issue is with the way this extension looks for configuration files, rather than with `zprint` itself. They provided quite detailed information about the problem.

If the extension could be brought into feature parity with `zprint` itself regarding the configuration file, that would be very nice! Until such a time I will continue to use a `.zprintrc` file.

**Comment by rflagreca** [comment]
Hi @MareinK! 

I'm glad you're finding this extension useful and thank you for filing an issue.  I've read through the issue you posted to the zprint repo and the responses to it and I agree - ideally vscode-clj-zprint should support all of the configuration options that zprint does.  I'll take a look in to implementing this soon.

**Comment by kkinnear** [comment]
Hello @rflagreca.  I was pleased to discover this VS Code extension!  Many thanks for building and distributing it.  There is a lot of overhead in publishing a VS Code extension it seems.

I have updated the zprint docs in the `1.2.0` release about "Getting zprint" to point people at this extension, and I was the one that responded to @MareinK's `.zprint.edn` issue.

I think that having this extension handle zprint configuration more like the stand alone zprint binaries do would be a good thing.  I am willing to try to help make that happen if that would be useful and interesting to you. I can think of contributing in either of the following ways:

1. I could contribute code to your extension which mimics zprint's approach to configuration files.  The code is easy, building and testing the result is harder for me at this point (see below).
2. It might be possible that I could modify the Clojurescript version of zprint to detect when the VS Code extension API is available, and use the VS Code file access (which you have used in this extension) to do the configuration directly.  This would mean that there was only one place the configuration files were processed.  Then you could remove the configuration file processing from this extension.  I have done something similar with detecting when a library was available in Clojure, and it worked out pretty well.  I'm not sure that I can pull that off in Clojurescript, but I have found some pointers that suggest it might work out.  Seems like a nice idea if I can make it would work.

I could have just done one of these and presented you with a pull request, but it looks there is a lot for me to learn about VS Code extensions in order to build and debug either of these things.  I am reasonably proficient in Clojurescript, but I have only barely installed VS Code -- enough to try out your extension.  But VS Code seems like a pretty interesting Clojure(script) environment, so learning more about it would be useful. I routinely use shadow-cljs to test zprint, but my usage is very basic.  I spent some time today reading about VS Code extensions and ... there is a lot there.   The minimal things I need to know to actually be helpful here are:

- How to build this extension with shadow-cljs.  
- How to get my local copy of VS Code to load and run the extension I have just built.
- Where to see any debugging `println`s I might put into the code

I expect I can figure out these things out with some experimentation, but unless you would find either (1) or (2) helpful, there is little point to investing the time to learn these things.  Let me know if I can be helpful.  Thanks!

**Comment by kkinnear** [comment]
For what it is worth, I have figured out how to build and run this extension.  Once I found `F5` and stopped trying to run the extension in the VS Code debugger, life became a lot better.

**Comment by rflagreca** [comment]
Hi @kkinnear, thanks for your very detailed comment on this issue and good to know that you have managed to build and run in a development environment.

IMO proposal 1 is best as it's something that we can do fairly simply and contain it to this extension.  Proposal 2 sounds like it would involve a bit more effort, co-ordination and overhead but happy to let you explore if you have the time and if you think it is a better solution. 

I am going to find it hard to find the time to work on this issue over the holidays so please do feel free to contribute a PR with your preferred solution and we can discuss there.

**Comment by kkinnear** [comment]
I too am busy over the holidays, so I don't expect to come up with a PR anytime until well after the new year (at best).  I'm good with approach #1.  The code is probably not as easy as I thought anyway, since zprint's configuration approach involves working its way up the directory tree from the current directory.  I'm going to have to dig into the VS Code API to figure out how to do that (and if it is even possible).  I don't know if VS Code will let me look "above" the current workspace or not.  Nor even how to find the current working directory.  But I'll look into that when I have time in the new year.

One thing I can do before that is to write up the current configuration approach that zprint uses so that you know what I'm thinking of doing.  Maybe I'll start a new issue for that.

**Comment by rflagreca** [comment]
Hi @kkinnear - I've a [simple solution](https://github.com/rflagreca/vscode-clj-zprint/pull/2) to this which uses the same logic I used to implement the `.zprintrc` support.  Then realised you had forked the repo and were probably working on your own solution - apologies! Obviously it;s not as sophisticated as the logic in zprint's configuration, however,  let me know what you think and if this is acceptable in the meantime.  I've tested locally in a test vscode workspace and seems to work fine - (I will add some automated testing at some point when I have the time to figure that out 😅 ).

**Comment by kkinnear** [comment]
Hello!  This is awkward.  While I just forked your repo the other day, I have been working on the extension in a cloned repository for several weeks.  I will submit the pull request in a few minutes.  Sorry I didn't get it done sooner!

The changes you have made make perfect sense as extensions of the existing approach.  There are a couple of issues that might trip people up, though.  The theory of zprint's configuration approach was to have sort of a "global" configuration in a user's configuration files (either `.zprintrc` or `.zprint.edn`), and then more specific, possibly project oriented configuration in a file located with the project itself.  Moreover, zprint won't even look for local, project oriented files unless the home directory configuration specifically allows this.  So doing either the project oriented or the home directory configuration but not both could be really confusing to people, I think.

That said, it was considerably more complex to mimic zprint's configuration practices in the extension, but I believe I've done so successfully.  I moved some code over from zprint and had to hack at it a bit to get it to fit into this new environment, but I think it works correctly now.

The other concern I have is security.  There is executable code in options maps, and so zprint reads in the options maps using the small Clojure interpreter (sci), to essentially "sandbox" the execution.  The extension currently doesn't do that, which may not be a problem in most cases, but it does kind of scare me a bit.

I'll explain all of this in more detail in the pull request, and you can see what you think and what you want to do.

**Comment by rflagreca** [comment]
Support for `.zprint.edn` configuration was added in `v0.0.3`
